### ISSUE TITLE
Can't run instance

### ISSUE THREAD

**Issue by moeenio** [ScReGr/calicode-gui#2]
Got this on npm test :
```
> calicode-gui@1.0.0 test /Users/locness/Documents/calicode-gui
> node index.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1253:19)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Function.listen (/Users/locness/Documents/calicode-gui/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/locness/Documents/calicode-gui/index.js:31:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by skyclo** [comment]
Something is currently running on port 80. Use another open port.

**Comment by moeenio** [comment]
How do I do that ?

**Comment by skyclo** [comment]
On your local copy change the 80 in this line to something like 8080 
https://github.com/ScReGr/calicode-gui/blob/bf1945783711022890577d63baf028563132bbfb/index.js#L31

**Comment by moeenio** [comment]
Ah yes, that works. Though it still shows it's listening on port 80
